/*
 * File: app/controller/Restaurant.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TileView.controller.Restaurant', {
    extend: 'Ext.app.Controller',

    models: [
        'Restaurant'
    ],
    stores: [
        'Restaurants'
    ],
    views: [
        'Restaurant',
        'MenuRestaurant',
        'RestaurantPanel'
    ],

    refs: [
        {
            ref: 'restaurant',
            selector: 'restaurant'
        }
    ],

    onButtonChange: function(btn, item) {
        var grid = this.getRestaurant();
        grid.features[0].setView(btn.viewMode);
    },

    onMenuitemClick: function(item, e, eOpts) {
        var grid = this.getRestaurant();
        grid.features[0].setView(item.viewMode);
    },

    onGridpanelItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        var contextMenu = Ext.create('TileView.view.MenuRestaurant');

        e.stopEvent();
        contextMenu.showAt(e.getXY());
        return false;
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        if (selected.length) {
            Ext.getCmp('tileViewPanel').update(selected[0].data);
        }
    },

    init: function(application) {
        this.control({
            "restopanel switchbuttonsegment": {
                change: this.onButtonChange
            },
            "splitbutton menuitem": {
                click: this.onMenuitemClick
            },
            "gridpanel": {
                itemcontextmenu: this.onGridpanelItemContextMenu,
                selectionchange: this.onGridpanelSelectionChange
            }
        });
    }

});
